---
- name: create gitlab user on gitlab node and managed servers
  hosts:       managed-servers,gitlab
  remote_user: "{{ user }}"
  become:      true
  vars:
    ansible_become_pass: "{{ password }}"
  tasks:
    - name: create gitlab users with no password
      user:
        name:       gitlab
        state:      present
        createhome: yes
        groups:     wheel,docker
        append:     yes
        password:   "!"

    - name: create temporary directory for ssh keypair
      file:
        path:  /home/{{ user }}/.tmp/
        state: directory
        mode:  '0700'
      run_once: True

    - name: generate an ssh keypair
      openssh_keypair:
        path:  "/home/{{ user }}/.tmp/id_rsa"
      run_once: True

    - name: read contents of public ssh key
      slurp:
        src:    "/home/{{ user }}/.tmp/id_rsa.pub"
      register: id_rsa_pub
      run_once: true

    - name: read contents of private ssh key
      slurp:
        src:    "/home/{{ user }}/.tmp/id_rsa"
      register: id_rsa
      run_once: true
    
    - name: delete temporary directory
      file:
        path:  "/home/{{ user }}/.tmp"
        state: absent

    - name: authorize public ssh key on managed servers and remove all others
      authorized_key:
        user:      gitlab
        key:       "{{ id_rsa_pub['content'] | b64decode }}"
        exclusive: yes
      when: inventory_hostname in groups['managed-servers']

    - name: print private ssh key to console
      debug:
        msg: |
          This is the private key that can be used to
          log in as 'gitlab' user to EVERY SERVER
          managed by your Gitlab instance.
          Create an instance-wide variable ID_RSA and store the key there.
          Never expose its contents anywhere else.

          {{ id_rsa['content'] | b64decode }}
      run_once: true
