---
- name:  deploy gitlab runner
  hosts:       runners
  remote_user: "{{ user }}"
  become:      true
  vars:
    ansible_become_pass: "{{ password }}"
  tasks:
    - name: copy gitlab-runner's compose file to remote host
      copy:
        src:  "../../compose-files/gitlab-runner/docker-compose.yml"
        dest: "/home/{{ user }}/gitlab-runner/docker-compose.yml"
    
    - name: startup gitlab-runner
      shell: "docker compose -f /home/{{ user }}/gitlab-runner/docker-compose.yml up -d"

    - name: register a runner
      shell: >
        docker exec -it gitlab-runner
        gitlab-runner register -n
        --url https://{{ hostvars[groups['gitlab'][0]].gitlab_url }}
        --registration-token {{ hostvars[inventory_hostname].registration_token }}
        --executor docker --description "Deployment Runner"
        --docker-image "docker:stable"
        --tag-list deployment
        --docker-privileged
