version: "3.6"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: ${GITLAB_EXTERNAL_URL}
    environment:
      GITLAB_ROOT_PASSWORD:   '${GITLAB_ROOT_PASSWORD}'
      GITLAB_OMNIBUS_CONFIG: |
        external_url          'https://${GITLAB_EXTERNAL_URL}'
        registry_external_url "https://${GITLAB_EXTERNAL_URL}:${REGISTRY_EXTERNAL_PORT}"
        letsencrypt['enable'] = true
    ports:
      - '80:80'
      - '443:443'
      - '2289:22'
      - '${REGISTRY_EXTERNAL_PORT}:${REGISTRY_EXTERNAL_PORT}'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '256m'

volumes:
  gitlab_config:
    driver: local
  gitlab_logs:
    driver: local
  gitlab_data:
    driver: local
